name = "Test application"
bundle_id = "com.example.test"
version = "0.1.0"
developer = "tas0dev"
entry = "entry.elf"
description = "Test application for demonstrating Binder"
icon = "icon.png"

resources = [
    "icon.png"
]