format = 1

[package]
id = "com.example.test"
name = "Test application"
version = "0.1.0"
vendor = "tas0dev"
kind = "application"

[application]
entry = "internal:test"
description = "Test application for demonstrating Binder"
