format = 1

[package]
id = "com.example.hello"
name = "Hello application"
version = "0.1.0"
vendor = "tas0dev"
kind = "application"

[application]
entry = "entry.elf"
description = "Hello application for demonstrating Binder"
icon = "icon.png"
resources = ["icon.png"]
